<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ITServiceDeskApp-6dcecd4a-4f54-41d4-8828-1091172c0b11</UserSecretsId>
    <DefaultItemExcludes>$(DefaultItemExcludes);out_temp\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="7.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.6" />
    <PackageReference Include="QuestPDF" Version="2024.7.1" />
    <PackageReference Include="QRCoder" Version="1.4.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="scripts\**\*.cs" />
  </ItemGroup>

</Project>

