// <auto-generated />
using ITServiceDeskApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ITServiceDeskApp.Migrations.Postgres;

[DbContext(typeof(PostgresApplicationDbContext))]
[Migration("20260926212303_AddMaintenanceExternalRepairOverrides")]
partial class AddMaintenanceExternalRepairOverrides
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
}
